######################################################################
# Automatically generated by qmake (2.01a) ?? ??? 20 13:46:12 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += ./sources
INCLUDEPATH += .

# Input
HEADERS += LinePoint.h MainWindow.h PanelDraw.h PanelTools.h
SOURCES += LinePoint.cpp main.cpp PanelDraw.cpp
